name: Run Postman Tests

on:
  push:
    branches: [ main ]

jobs:
  api-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Newman
        run: npm install -g newman

      - name: Check files
        run: ls -R

      - name: Run Postman Collection
        run: newman run fakestore.collection.json -e fakestore.environment.json
